name: Packer and Terraform
on: push
jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0
     
    - name: Create ami directory
      run: |
          mkdir ami && cp webapp/app.py webapp/requirements.txt webapp/packer_amibuild.json webapp/app.service webapp/cloudwatch-config.json ami
          cd ami && ls -all
          
    - name: Check working directory
      run: |
          cd ami
          pwd
          ls -all
  
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: |
        cd aws-infra
        terraform init
        
    - name: Format Terraform
      run: |
        cd aws-infra
        terraform fmt
        

        
    - name: Use values.tfvars file
      run: |
        cd aws-infra
        cat << EOF > values.tfvars
        ${{ secrets.VALUES }}
        EOF

    - name: Plan Terraform
      run: |
        cd aws-infra
        terraform plan -var-file=values.tfvars -var="ami=ami-09a63b310aca20781"
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
        
    - name: Refresh Terraform
      run: |
        cd aws-infra
        terraform refresh -var-file=values.tfvars -var="ami=ami-09a63b310aca20781"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
        
    - name: Build AWS infrastructure using Terraform 
      id: apply
      run: |
        cd aws-infra
        terraform apply -var-file=values.tfvars --auto-approve -var="ami=ami-09a63b310aca20781"
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2

    - name: Destroy Terraform resources if apply failed
      if: ${{ failure() }}
      run: |
        cd aws-infra
        terraform destroy -var-file=values.tfvars --auto-approve -var="ami=ami-09a63b310aca20781"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
