name: Packer and Terraform
on: push
jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: |
        cd aws-infra
        terraform init
        
    - name: Format Terraform
      run: |
        cd aws-infra
        terraform fmt
    
    - name: Use values.tfvars file
      run: |
        cd aws-infra
        printf '%s\n' "${{ secrets.VALUES }}" > values.tfvars
        ls -all
        
    - name: Print values.tfvars file
      run: |
        cd aws-infra
        cat values.tfvars

    - name: Apply Terraform to build infrastructure
      run: |
        cd aws-infra
        terraform apply -var-file=values.tfvars --auto-approve
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
