name: Packer and Terraform
on: push
jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create ami directory
      run: |
          mkdir ami && cp webapp/app.py webapp/requirements.txt webapp/packer_amibuild.json webapp/app.service webapp/cloudwatch-config.json ami
          cd ami && ls -all
          
    - name: Check working directory
      run: |
          cd ami
          pwd
          ls -all
          
    - name: Build AMI using Packer
      uses: hashicorp/packer-github-actions@master
      with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer_amibuild.json
          working_directory: ami
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
    - name: Print manifest.json
      run: cat ami/manifest.json
      
    - name: Install AWS CLI
      run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: |
        cd aws-infra
        terraform init
        
    - name: Format Terraform
      run: |
        cd aws-infra
        terraform fmt
          
    - name: Copy AMI id
      run: |
          cd aws-infra
          AMI_ID=$(jq -r '.builds[-1].artifact_id' ./ami/manifest.json | cut -d ":" -f2)
          echo $AMI_ID
    
    - name: Use values.tfvars file
      run: |
        cd aws-infra
        echo "${{ secrets.VALUES_TF }}" > values.tfvars

    - name: Apply Terraform to build infrastructure
      run: |
        cd aws-infra
        terraform apply -var-file=values.tfvars -var="ami=$AMI_ID" --auto-approve
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
