name: Packer and Terraform
on: push
jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0
      
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: |
        cd aws-infra
        terraform init
        
    - name: Format Terraform
      run: |
        cd aws-infra
        terraform fmt

    - name: Plan Terraform
      run: |
        cd aws-infra
        terraform plan -var-file=values.tfvars
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
        
    - name: Build infrastructure using Terraform 
      run: |
        cd aws-infra
        terraform apply -var-file=values.tfvars --auto-approve
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
