name: Pull Request Raised Workflow
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISABLE_DATABASE: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd webapp
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          cd webapp
          python test_app.py
      - name: Run pylint
        run: |
          cd webapp
          pip install pylint
          pylint *.py
