name: Terraform Apply
on:
  workflow_run:
    workflows: ["Build AMI"]
    types:
      - completed

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Initialize Terraform'
      run: |
        cd aws-infra
        terraform init
        
    - name: 'Format Terraform'
      run: |
        cd aws-infra
        terraform fmt
    
    - name: Create values.tf file
      run: |
        cd aws-infra
        echo "${{ secrets.VALUES_TF }}" > values.tf

    - name: 'Apply Terraform'
      run: |
        cd aws-infra
        terraform apply -var-file=values.tfvars --auto-approve
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
